# Generated by Django 3.1.5 on 2021-03-20 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20210219_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='friendly_name',
            field=models.CharField(help_text='This name will be displayed when selecting a category for a new product entry', max_length=254, null=True),
        ),
    ]
