# Generated by Django 3.1.7 on 2021-03-22 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20210219_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='friendly_name',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
