# Generated by Django 3.1.5 on 2021-03-20 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20210320_1534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='language',
        ),
    ]
