# Generated by Django 3.1.5 on 2021-03-20 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_product_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=254)),
                ('year_of_birth', models.PositiveIntegerField(blank=True, null=True)),
                ('year_of_death', models.PositiveIntegerField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('external_links', models.URLField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, max_length=1024, null=True, verbose_name='Image URL')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
