# Generated by Django 3.1.5 on 2021-03-16 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_friendly_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='friendly_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
