# Generated by Django 3.1.5 on 2021-03-16 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20210316_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='friendly_name',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
