# Generated by Django 3.1.5 on 2021-03-17 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20210316_1406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='book_title',
        ),
        migrations.RemoveField(
            model_name='author',
            name='name_and_surname',
        ),
        migrations.RemoveField(
            model_name='publisher',
            name='book_title',
        ),
        migrations.RemoveField(
            model_name='publisher',
            name='publisher_name',
        ),
        migrations.AddField(
            model_name='author',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='products.product'),
        ),
        migrations.AddField(
            model_name='publisher',
            name='publisher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='products.product'),
        ),
    ]
