# Generated by Django 3.1.7 on 2021-03-22 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20210322_0031'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=254)),
                ('description', models.TextField(blank=True)),
                ('external_links', models.URLField(blank=True)),
                ('image_url', models.URLField(blank=True, max_length=1024, verbose_name='Image URL')),
                ('image', models.ImageField(blank=True, upload_to='')),
            ],
        ),
    ]
