# Generated by Django 3.1.5 on 2021-03-19 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20210317_0145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='year_of_birth',
            field=models.PositiveIntegerField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='year_of_death',
            field=models.PositiveIntegerField(blank=True, max_length=4, null=True),
        ),
    ]
