# Generated by Django 3.1.5 on 2021-03-19 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20210319_0150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='name',
            new_name='author_name',
        ),
        migrations.RenameField(
            model_name='publisher',
            old_name='publisher',
            new_name='publisher_name',
        ),
    ]
