# Generated by Django 3.1.5 on 2021-03-20 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20210319_1555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publisher',
            name='publisher_name',
        ),
        migrations.AddField(
            model_name='publisher',
            name='name',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='author',
            name='image_url',
            field=models.URLField(blank=True, max_length=1024, null=True, verbose_name='Image URL'),
        ),
        migrations.AlterField(
            model_name='author',
            name='year_of_birth',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='year_of_death',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(blank=True, help_text='Select a category for this book', to='products.Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, max_length=1024, null=True, verbose_name='Image URL'),
        ),
        migrations.AlterField(
            model_name='product',
            name='publisher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='products.publisher'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, max_length=254, null=True, unique=True, verbose_name='SKU'),
        ),
        migrations.AlterField(
            model_name='product',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='image_url',
            field=models.URLField(blank=True, max_length=1024, null=True, verbose_name='Image URL'),
        ),
    ]
